### ISSUE TITLE
quickmongo not working

### ISSUE THREAD

**Issue by Ruchit3425** [octagonemusic/Discord.js-v13-Bot#13]

**Comment by octagonemusic** [comment]
What exactly isn't working? Can you please explain your issue in more detail and show your error if any?

**Comment by Ruchit3425** [comment]
Bro the error coming that Database is not a constructor in new Database linr

मंगल, 7 सितं 2021, 09:31 को Octagone Music ***@***.***> ने
लिखा:

**Comment by octagonemusic** [comment]
Can you please show the line where the error has occurred and the file name?

**Comment by Ruchit3425** [comment]
ohk i solved it

**Comment by Ruchit3425** [comment]
thx for help

**Comment by octagonemusic** [comment]
No problem! I will be closing this issue now!
